_VIM.keymap.set("n", "<Leader>tn", ":TodoNew<CR>")
_VIM.keymap.set("n", "<Leader>td", ":TodoDone<CR>")
_VIM.keymap.set("n", "<Leader>tt", ":TodoBorderWindow<CR>")
_VIM.keymap.set("n", "<Leader>tb", ":TodoBuffers<CR>")
_VIM.keymap.set("n", "<Leader>tx", ":TodoThisWeekTemplate<CR>")
_VIM.keymap.set("n", "<Leader>te", ":TodoNextWeekTemplate<CR>")
_VIM.keymap.set("n", "<Leader>tl", ":OpenListTodoThings<CR>")
_VIM.keymap.set("n", "<Leader>th", ":OpenHelpWindow<CR>")
