local new_branch_content = "║    ├─ "
local end_branch_content = "║    └─ "

local day1="- Lundi -"
local day2="- Mardi -"
local day3="- Mercredi -"
local day4="- Jeudi -"
local day5="- Vendredi -"
local day6="- Samedi -"
local day7="- Dimanche -"
local day8="╚══════════════════════════════════════════════════════════════════════════════════════════════════╝"
local day1_Middle="┃ - Lundi - ┃"
local day2_Middle="┃ - Mardi - ┃"
local day3_Middle="┃ - Mercredi - ┃"
local day4_Middle="┃ - Jeudi - ┃"
local day5_Middle="┃ - Vendredi - ┃"
local day6_Middle="┃ - Samedi - ┃"
local day7_Middle="┃ - Dimanche - ┃"
local day1_Middle_Unmarked="│ - Lundi - │"
local day2_Middle_Unmarked="│ - Mardi - │"
local day3_Middle_Unmarked="│ - Mercredi - │"
local day4_Middle_Unmarked="│ - Jeudi - │"
local day5_Middle_Unmarked="│ - Vendredi - │"
local day6_Middle_Unmarked="│ - Samedi - │"
local day7_Middle_Unmarked="│ - Dimanche - │"
local day1_Top_Outline="┏━━━━━━━━━━━┓   "
local day1_Bot_Outline="┗━┯━━━━━━━━━┛   "
local day2_Top_Outline="┏━━━━━━━━━━━┓  "
local day2_Bot_Outline="┗━┯━━━━━━━━━┛  "
local day3_Top_Outline="┏━━━━━━━━━━━━━━┓   "
local day3_Bot_Outline="┗━┯━━━━━━━━━━━━┛   "
local day4_Top_Outline="┏━━━━━━━━━━━┓ "
local day4_Bot_Outline="┗━┯━━━━━━━━━┛ "
local day5_Top_Outline="┏━━━━━━━━━━━━━━┓  "
local day5_Bot_Outline="┗━┯━━━━━━━━━━━━┛  "
local day6_Top_Outline="┏━━━━━━━━━━━━┓"
local day6_Bot_Outline="┗━┯━━━━━━━━━━┛"
local day7_Top_Outline="┏━━━━━━━━━━━━━━┓ "
local day7_Bot_Outline="┗━┯━━━━━━━━━━━━┛ "
local day1_Top_Outline_Unmarked="┌───────────┐   "
local day1_Bot_Outline_Unmarked="└─┬─────────┘   "
local day2_Top_Outline_Unmarked="┌───────────┐  "
local day2_Bot_Outline_Unmarked="└─┬─────────┘  "
local day3_Top_Outline_Unmarked="┌──────────────┐   "
local day3_Bot_Outline_Unmarked="└─┬────────────┘   "
local day4_Top_Outline_Unmarked="┌───────────┐ "
local day4_Bot_Outline_Unmarked="└─┬─────────┘ "
local day5_Top_Outline_Unmarked="┌──────────────┐  "
local day5_Bot_Outline_Unmarked="└─┬────────────┘  "
local day6_Top_Outline_Unmarked="┌────────────┐"
local day6_Bot_Outline_Unmarked="└─┬──────────┘"
local day7_Top_Outline_Unmarked="┌──────────────┐ "
local day7_Bot_Outline_Unmarked="└─┬────────────┘ "

return {
	new_branch_content = new_branch_content,
	end_branch_content = end_branch_content,

	day1 = day1,
	day2 = day2,
	day3 = day3,
	day4 = day4,
	day5 = day5,
	day6 = day6,
	day7 = day7,
	day1_Middle = day1_Middle,
	day2_Middle = day2_Middle,
	day3_Middle = day3_Middle,
	day4_Middle = day4_Middle,
	day5_Middle = day5_Middle,
	day6_Middle = day6_Middle,
	day7_Middle = day7_Middle,
	day1_Top_Outline = day1_Top_Outline,
	day2_Top_Outline = day2_Top_Outline,
	day3_Top_Outline = day3_Top_Outline,
	day4_Top_Outline = day4_Top_Outline,
	day5_Top_Outline = day5_Top_Outline,
	day6_Top_Outline = day6_Top_Outline,
	day7_Top_Outline = day7_Top_Outline,
	day1_Bot_Outline = day1_Bot_Outline,
	day2_Bot_Outline = day2_Bot_Outline,
	day3_Bot_Outline = day3_Bot_Outline,
	day4_Bot_Outline = day4_Bot_Outline,
	day5_Bot_Outline = day5_Bot_Outline,
	day6_Bot_Outline = day6_Bot_Outline,
	day7_Bot_Outline = day7_Bot_Outline,

	day1_Middle_Unmarked = day1_Middle_Unmarked,
	day2_Middle_Unmarket = day2_Middle_Unmarked,
	day3_Middle_Unmarket = day3_Middle_Unmarked,
	day4_Middle_Unmarket = day4_Middle_Unmarked,
	day5_Middle_Unmarket = day5_Middle_Unmarked,
	day6_Middle_Unmarket = day6_Middle_Unmarked,
	day7_Middle_Unmarket = day7_Middle_Unmarked,
	day1_Top_Outline_Unmarket = day1_Top_Outline_Unmarked,
	day2_Top_Outline_Unmarket = day2_Top_Outline_Unmarked,
	day3_Top_Outline_Unmarket = day3_Top_Outline_Unmarked,
	day4_Top_Outline_Unmarket = day4_Top_Outline_Unmarked,
	day5_Top_Outline_Unmarket = day5_Top_Outline_Unmarked,
	day6_Top_Outline_Unmarket = day6_Top_Outline_Unmarked,
	day7_Top_Outline_Unmarket = day7_Top_Outline_Unmarked,
	day1_Bot_Outline_Unmarket = day1_Bot_Outline_Unmarked,
	day2_Bot_Outline_Unmarket = day2_Bot_Outline_Unmarked,
	day3_Bot_Outline_Unmarket = day3_Bot_Outline_Unmarked,
	day4_Bot_Outline_Unmarket = day4_Bot_Outline_Unmarked,
	day5_Bot_Outline_Unmarket = day5_Bot_Outline_Unmarked,
	day6_Bot_Outline_Unmarket = day6_Bot_Outline_Unmarked,
	day7_Bot_Outline_Unmarket = day7_Bot_Outline_Unmarked,
}
